- name: OpenGrep Security Scan
  uses: maloma7/opengrep-action@v1
  with:
    paths: 'src app'
    output-format: 'sarif'
    output-file: 'opengrep-results.sarif'

 - name: Upload OpenGrep scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'opengrep-results.sarif'
